# Generated by Django 4.2.4 on 2023-09-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_message_created_message_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated_models', '-created']},
        ),
    ]
